name: Check pull request

on:
  # Runs on pull requests only
  push:
    pullrequest:

jobs:
  # Single deploy job since we're just deploying
  pullrequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: 16
      - run: yarn install

      # The linter is run here. Maybe there's a faster way to lint a react project
      - run: yarn build
        env:
          GENERATE_SOURCEMAP: false
          CI: false
